apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-website-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaskwebsite
  template:
    metadata:
      labels:
        app: flaskwebsite
    spec:
      containers:
      - name: flaskwebsite
        image: devnpaksuksacr001.azurecr.io/flaskwebsite:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-website-service
spec:
  selector:
    app: flaskwebsite
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 5000
  type: LoadBalancer