apiVersion: v1
kind: Service
metadata:
    name: "kingoliver2-5755"
    labels:
        app: "kingoliver2-5755"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "kingoliver2-5755"