name: Plan & Deploy to Azure - Dev Containers

on:
  push:
    branches:
      - main
    paths:
      - '007_Containers/**'
  pull_request:
    branches:
      - main
    paths:
      - '007_Containers/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  pull-requests: write

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  ARM_USE_AZUREAD: true

jobs:
  validate-and-plan:
    name: Validate and Plan
    runs-on: ubuntu-latest
    environment: dev
    defaults:
      run:
        working-directory: ./007_Containers

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
      
      - name: 'Az CLI login'
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: Terraform Fmt
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform init -backend-config="resource_group_name=tf-rg" -backend-config="storage_account_name=${{ secrets.TF_STATE_STORAGE_ACCOUNT }}" -backend-config="container_name=terraform"

      - name: Terraform Validate
        run: terraform validate

      - name: tfsec
        uses: aquasecurity/tfsec-pr-commenter-action@v1.3.1
        with:
          tfsec_args: --soft-fail
          github_token: ${{ github.token }}
    
      - name: Terraform Plan
        run: terraform plan -var-file="infra_environment_dev.tfvars" -out=main-dev.tfplan

      - name: Publish Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan-dev
          path: ./007_Containers/main-dev.tfplan
    
  apply:
    needs: validate-and-plan
    name: Apply & Deploy to Azure
    runs-on: ubuntu-latest
    environment: dev
    defaults:
      run:
        working-directory: ./007_Containers

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
      
      - name: 'Az CLI login'
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: Terraform Init
        run: terraform init -backend-config="resource_group_name=tf-rg" -backend-config="storage_account_name=${{ secrets.TF_STATE_STORAGE_ACCOUNT }}" -backend-config="container_name=terraform"

      - name: Download Terraform Plan
        uses: actions/download-artifact@v4
        with:
          name: tfplan-dev
          path: ./007_Containers

      - name: Terraform Apply
        run: terraform apply -auto-approve "./main-dev.tfplan"

      # - name: Azure CLI script
      #   uses: azure/cli@v2
      #   with:
      #     azcliversion: latest
      #     inlineScript: |
      #       az account show

      # - name: Azure PowerShell script
      #   uses: azure/powershell@v2
      #   with:
      #     azPSVersion: "latest"
      #     inlineScript: |
      #       Get-AzContext